services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://kata:kataaubay@db:5432/kata
    volumes:
      - ./app/resources:/app/resources
    depends_on:
      - db

  db:
    build:
      context: docker/db
      dockerfile: Dockerfile
    image: postgres:15
    environment:
      POSTGRES_USER: kata
      POSTGRES_PASSWORD: kataaubay
      POSTGRES_DB: kata
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ihm/kata-aubay
      dockerfile: ../../docker/front/Dockerfile # adjust path if Dockerfile is in docker/angular
    ports:
      - "4200:4200"
    volumes:
      - ./ihm/kata-aubay:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - api

